<div class="h-full flex flex-col justify-top pt-20">
    <p class="text-eventit-500 text-center font-bold text-6xl" data-lang="Conditions générales d'utilisation|Terms of Use">Conditions générales d'utilisation</p>
    <div class="max-w-screen-2xl pt-20 p-6 self-center">
       <h2 class="text-eventit-500" data-lang="Préambule|Preamble">Préambule</h2>
       <p class="text-lg" data-lang="Les présentes Conditions Générales d'Utilisation (CGU) régissent l'utilisation du site internet [Nom de votre site] ainsi que des services proposés par [Nom de votre entreprise], ci-après dénommée 'la Société'.|These General Terms of Use (GTU) govern the use of the website [Your site name] and the services offered by [Your company name], hereinafter referred to as 'the Company'.">Les présentes Conditions Générales d'Utilisation (CGU) régissent l'utilisation du site internet [Nom de votre site] ainsi que des services proposés par [Nom de votre entreprise], ci-après dénommée "la Société".</p>
    </div>
    <div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Acceptation des conditions|Acceptance of Conditions">Acceptation des conditions</h2>
    <p class="text-lg" data-lang="En accédant au site [Nom de votre site] ou en utilisant nos services, vous acceptez sans réserve les présentes CGU. Si vous n'acceptez pas ces conditions, veuillez ne pas accéder au site ou utiliser nos services.|By accessing the site [Your Site Name] or using our services, you unreservedly accept these GTU. If you do not accept these conditions, please do not access the site or use our services.">En accédant au site [Nom de votre site] ou en utilisant nos services, vous acceptez sans réserve les présentes CGU. Si vous n'acceptez pas ces conditions, veuillez ne pas accéder au site ou utiliser nos services.</p>
</div>
<div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Utilisation du site|Site Usage">Utilisation du site</h2>
    <p class="text-lg" data-lang="Vous vous engagez à utiliser le site [Nom de votre site] conformément aux lois en vigueur et aux présentes CGU. Vous acceptez de ne pas utiliser le site à des fins illicites ou interdites par les présentes conditions.|You agree to use the site [Your Site Name] in accordance with current laws and these GTU. You agree not to use the site for illegal purposes or purposes prohibited by these conditions.">Vous vous engagez à utiliser le site [Nom de votre site] conformément aux lois en vigueur et aux présentes CGU. Vous acceptez de ne pas utiliser le site à des fins illicites ou interdites par les présentes conditions.</p>
</div>
<div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Protection des Données|Data Protection">Protection des Données</h2>
    <p class="text-lg" data-lang="La Société s'engage à protéger vos données personnelles conformément à sa Politique de Confidentialité. En utilisant nos services, vous consentez à la collecte, au traitement et à l'utilisation de vos données personnelles telles que décrites dans ladite Politique de Confidentialité.|The Company commits to protecting your personal data in accordance with its Privacy Policy. By using our services, you consent to the collection, processing, and use of your personal data as described in the said Privacy Policy.">La Société s'engage à protéger vos données personnelles conformément à sa Politique de Confidentialité. En utilisant nos services, vous consentez à la collecte, au traitement et à l'utilisation de vos données personnelles telles que décrites dans ladite Politique de Confidentialité.</p>
</div>
<div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Propriété Intellectuelle|Intellectual Property">Propriété Intellectuelle</h2>
    <p class="text-lg" data-lang="Le contenu du site [Nom de votre site], y compris mais sans s'y limiter les textes, les images, les graphiques, les logos et les vidéos, est la propriété intellectuelle de la Société et est protégé par les lois sur le droit d'auteur et les marques commerciales.|The content of the site [Your Site Name], including but not limited to texts, images, graphics, logos, and videos, is the intellectual property of the Company and is protected by copyright and trademark laws.">Le contenu du site [Nom de votre site], y compris mais sans s'y limiter les textes, les images, les graphiques, les logos et les vidéos, est la propriété intellectuelle de la Société et est protégé par les lois sur le droit d'auteur et les marques commerciales.</p>
</div>
<div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Responsabilité|Liability">Responsabilité</h2>
    <p class="text-lg" data-lang="La Société s'efforce de fournir des informations précises et à jour sur son site, mais ne peut garantir l'exactitude, l'exhaustivité ou la pertinence de ces informations. En aucun cas, la Société ne pourra être tenue responsable de tout dommage direct, indirect, accessoire, spécial, punitif ou consécutif découlant de l'utilisation ou de l'incapacité à utiliser le site ou les services de la Société.|The Company strives to provide accurate and up-to-date information on its site, but cannot guarantee the accuracy, completeness, or relevance of this information. In no case can the Company be held liable for any direct, indirect, incidental, special, punitive, or consequential damage arising from the use or inability to use the site or the Company's services.">La Société s'efforce de fournir des informations précises et à jour sur son site, mais ne peut garantir l'exactitude, l'exhaustivité ou la pertinence de ces informations. En aucun cas, la Société ne pourra être tenue responsable de tout dommage direct, indirect, accessoire, spécial, punitif ou consécutif découlant de l'utilisation ou de l'incapacité à utiliser le site ou les services de la Société.</p>
</div>
<div class="max-w-screen-2xl pt-10 p-6 self-center">
    <h2 class="text-eventit-500" data-lang="Modification des Conditions|Modification of Conditions">Modification des Conditions</h2>
    <p class="text-lg" data-lang="La Société se réserve le droit de modifier à tout moment les présentes CGU. Les modifications prendront effet dès leur publication sur le site. Il vous incombe de consulter régulièrement les CGU pour prendre connaissance de toute modification.|The Company reserves the right to modify these GTU at any time. The modifications will take effect as soon as they are published on the site. It is your responsibility to regularly consult the GTU to be aware of any modifications.">La Société se réserve le droit de modifier à tout moment les présentes CGU. Les modifications prendront effet dès leur publication sur le site. Il vous incombe de consulter régulièrement les CGU pour prendre connaissance de toute modification.</p>
</div>
    <div class="max-w-screen-2xl pt-10 p-6 self-center">
       <h2 class="text-eventit-500"data-lang="Droit Applicable et Juridiction|Applicable Law and Jurisdiction">Droit Applicable et Juridiction</h3>
       <p class="text-lg" data-lang="Les présentes CGU sont régies par le droit en vigueur. En cas de litige, les tribunaux compétents seront ceux désignés par la loi applicable.Les présentes CGU sont régies par le droit en vigueur. En cas de litige, les tribunaux compétents seront ceux désignés par la loi applicable.|The present GCU are governed by current law. In the event of a dispute, the competent courts will be those designated by the applicable law. In the event of a dispute, the competent courts will be those designated by the applicable law.">Les présentes CGU sont régies par le droit en vigueur. En cas de litige, les tribunaux compétents seront ceux désignés par la loi applicable.Les présentes CGU sont régies par le droit en vigueur. En cas de litige, les tribunaux compétents seront ceux désignés par la loi applicable.</p>
    </div>
    <div class="max-w-screen-2xl pt-10 pb-32 p-6 self-center">
    <p class="text-lg" data-lang="En acceptant ces CGU, vous reconnaissez avoir lu, compris et accepté toutes les dispositions qui y sont contenues. Si vous avez des questions concernant les présentes CGU, veuillez nous contacter à l'adresse [adresse e-mail de contact].|By accepting these GTU, you acknowledge having read, understood, and accepted all the provisions contained herein. If you have any questions regarding these GTU, please contact us at [contact email address].">En acceptant ces CGU, vous reconnaissez avoir lu, compris et accepté toutes les dispositions qui y sont contenues. Si vous avez des questions concernant les présentes CGU, veuillez nous contacter à l'adresse [adresse e-mail de contact].</p>
</div>
</div>